site_name: coproc Package
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt 
  features:
    - navigation.expand
repo_url: https://github.com/devincornell/coproc
repo_name: devincornell/coproc
